# Generated by Django 4.1.13 on 2024-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
